config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users
  root to: "home#index"
  resources :home
  resources :categories, only: [:index, :new, :create] do
    resources :contents do
      resources :comments
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :contents
  has_many :users, through: :contents

  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :content

  validates :comment, presence: true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contents
  has_many :categories
  has_many :categories, through: :contents
  has_many :comments

  validates :name, presence: true, uniqueness: true
  validates :info, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :info])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :move_to_home, except: [:show]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.valid?
      @category.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def move_to_home
    unless user_signed_in?
      redirect_to root_path
    end
  end

  def category_params
    params.require(:category).permit(:name).merge(user_id: current_user.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :move_to_home, except: [:index, :show]

  def create
    @category = Category.find(params[:category_id])
    @content = Content.find(params[:content_id])
    @comment = @content.comments.new(comment_params)
    if @comment.valid?
      @comment.save
      ActionCable.server.broadcast 'comment_channel', content: @comment, name: current_user.name, at: l(@comment.created_at)
      # redirect_to category_content_path(@category, @content)
    else
      render "@content/show"
    end
  end

  private

  def move_to_home
    unless user_signed_in?
      redirect_to root_path
    end
  end

  def comment_params
    params.require(:comment).permit(:comment, :content_id).merge(user_id: current_user.id)
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :move_to_home, except: [:index, :show]

  def index
    @category = Category.find(params[:category_id])
    @contents = Content.where(category_id: params[:category_id])
    @content = Content.new
  end

  def create
    @category = Category.find(params[:category_id])
    @content = @category.contents.new(content_params)
    if @content.valid?
      @content.save
      redirect_to action: :index
    else
      redirect_to root_path
    end
  end

  def show
    @content = Content.find(params[:id])
    @category = Category.find(params[:category_id])
    @comments = Comment.where(content_id: params[:id])
    @comment = Comment.new
  end

  private

  def move_to_home
    unless user_signed_in?
      redirect_to root_path
    end
  end

  def content_params
    params.require(:content).permit(:content, :category_id).merge(user_id: current_user.id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def new
    @content = Content.new
  end

  def index
    @categories = Category.all
    @contents = Content.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_categories_bar.html.erb
<div class="category-area">
  <div class="create-category-area">
    <% if user_signed_in? %>
      <%=link_to "新しいカテゴリーを作成する", new_category_path %>
    <% else %>
      <%= "カテゴリーの作成はログインが必要です" %>
    <% end %>
  </div>
  <h1>ーカテゴリー一覧ー</h1>
  <div class="categories">
    <% @categories.each do |category| %>
    <div class="category-name">
      <%= link_to category.name, category_contents_path(category.id) %>
      (<%= category.contents.size %>)
    </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
 
  <div class="create-category">

    <div class="create-area5">
    <%= render 'shared/error_messages', model: @category %>

    <%=form_with model: @category, local: true do |f|%>
      <p class="p1">新しいカテゴリーを作成します</p>
      <div class="category-form">
        <%= f.text_field :name, class: 'input-category-name', placeholder: 'カテゴリー名を入力'%>
      </div>
      <div class="category-btn">
        <%= f.submit class: 'input-category-btn' %>
      </div>
      <div class="category-btn">
        <%= link_to "Back", root_path %>
      </div>

    <% end %>
    </div>
  </div>

app/views/comments/new.html.erb
<div class="create-area">
  <% if user_signed_in? %>
    <%= form_with model: [@category, @content, @comment], class: "form", local: true do |f|%>
      <form class="form">
        <div class="form2">  
          <%= f.text_area :comment, placeholder: 'type a comment', class: 'input-comment', id: "input-comment" %>
        </div> 
        <%= f.submit 'SEND', class: 'send-btn' %>
      </form>
    <% end %>
  <% else %>
    <%= "コメントするにはログインが必要です"%>
  <% end %>
</div>

app/views/contents/_contents.html.erb
  <div class="content-area">
    <h1>ーコンテント一覧ー</h1>
    <%= link_to "/" do %>
      <button>戻る</button>
    <% end %>
    <% @contents.reverse_each do |content| %>
      <%= link_to category_content_path(@category, content)  do %>
      <div class="contents-container">
          <h1 class="content-top">
              <%= content.content %>
          </h1>
          <div class="content-low">
            <ul class="content-info">
                <li> 作成者：<%= content.user.name %></li>
                <li> カテゴリー：<%= content.category.name %></li>
                <li> コメント数：<%= content.comments.size %></li>
            </ul>
          </div>
      </div>
      <% end %>
    <% end %>
  </div>

app/views/contents/_create_content.erb
  <div class="create-area">
    <% if user_signed_in? %>
      <%= form_with model: [@category, @content], class: "form", local: true do |f|%>
        <form class="create-form">
          <div class="form2">  
            <%= f.text_area :content, placeholder: 'type a content', class: 'input-content' %>
          </div> 
          <%= f.submit 'SEND', class: 'send-btn' %>
        </form>
      <% end %>
    <% else %>
      <%= "コンテントの作成にはログインが必要です" %>
    <% end %>
  </div>

app/views/contents/index.html.erb
  <div class="content-area2">
    <div class="content-area3">
      <%= render "contents"%>
    </div>
    <div class="create-content-area">
      <%= render "create_content"%>
    </div>
  </div>

app/views/contents/show.html.erb
<div class="content-area3">
  <%# <div> %>
    <div class="area3">
      <div class="show-content">
        <div class="content-top2">
            <%= @content[:content] %>
        </div>
        <div class="content-low">
          <ul class="content-info">
              <li> 作成者：<%= @content.user.name %></li>
              <li> カテゴリー：<%= @content.category.name %></li>
              <li> コメント数：<%= @content.comments.size %></li>
          </ul>
        </div>
      </div>
      <h1>ーコメント一覧ー</h1>
      <%= link_to category_contents_path(@category.id) do %>
        <button>戻る</button>
      <% end %>
        <div class="show-comment"id="show-comment">
          <% @comments.reverse_each do |comment| %>
          <div class="comment" >
            <div class="comment-top">
              <%= comment.comment %>
            </div>
            <div class="comment-low">
              <ul class="comment-info">
                <li>ユーザー名：<%= comment.user.name %></li>
                <li>コメント日時：<%= l comment.created_at %></li>
              </ul>
            </div>
          </div>
          <% end %>
        </div>
    </div>
    <div class="create-comment-area">
      <%= render template: "comments/new"%>
    </div>
  <%# </div> %>
</div>

app/views/home/index.html.erb
<div class="wrapper">
  <div class="categories-bar">
    <%= render "categories/categories_bar" %>
  </div>

  <div class="content-area">
    <h1>ーコンテント一覧ー</h1>
      <% @contents.each do |content| %>
        <%= link_to category_content_path(content.category, content)  do %>
        <div class="contents-container">
            <h1 class="content-top">
                <%= content.content %>
            </h1>
            <div class="content-low">
              <ul class="content-info">
                  <li> 作成者：<%= content.user.name %></li>
                  <li> カテゴリー：<%= content.category.name %></li>
                  <li> コメント数：<%= content.comments.size %></li>
              </ul>
            </div>
          <% end %>
        </div>
        <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GolfChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <%=link_to '/' do %>
        <div class="inner-header">
          <div>
          <%= image_tag 'golf_logo.png', class: "golf-image" %>
          </div>
          <h1 class="title"> GOLF CHAT </h1>
        </div>
      <% end %>

      <div class="input-user">
        <% if user_signed_in?%>
          <%= link_to current_user.name, edit_user_registration_path %>
          <%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "サインイン", new_user_session_path %>
          <%= link_to "新規登録", new_user_registration_path %>
        <% end %>
      </div>
    </header>

    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>